<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\Brand;

class BrandSeeder extends Seeder
{
    public function run(): void
    {
        $brands = [
            'Abarth',
            'AC',
            'Acura',
            'AIXAM',
            'Alfa Romeo',
            'Alpine',
            'Arash',
            'Ariel',
            'Artega',
            'Ascari',
            'Aston Martin',
            'Audi',
            'AvtoVAZ',
            'BAIC',
            'Bentley',
            'BMW',
            'Borgward',
            'Brilliance Auto',
            'Bristol',
            'Bufori',
            'Bugatti',
            'Buick',
            'BYD',
            'Byton',
            'Cadillac',
            'Campagna',
            'Caterham',
            'Changan',
            'Changhe',
            'Chery',
            'Chevrolet',
            'Chrysler',
            'Citroen',
            'Coda',
            'CT&T United',
            'Dacia',
            'Daewoo',
            'DAF',
            'Daihatsu',
            'Datsun',
            'Dodge',
            'Donkervoort',
            'DS Automobile',
            'Ferrari',
            'Fiat',
            'Fisker',
            'Force Motors',
            'Ford',
            'Foton',
            'GAZ',
            'Geely',
            'Genesis',
            'Ginetta',
            'GMC',
            'Great Wall',
            'Haima',
            'Hino',
            'Holden',
            'Honda',
            'Hyundai',
            'Iconic',
            'Infiniti',
            'Isuzu',
            'JAC',
            'Jaguar',
            'Jeep',
            'Jetour',
            'JMC',
            'Kia',
            'Koenigsegg',
            'Lamborghini',
            'Lancia',
            'Land Rover',
            'Landwind',
            'Lexus',
            'Lifan',
            'Lincoln',
            'Lotus',
            'Lucid',
            'Luxgen',
            'Magna Steyr',
            'Mahindra',
            'Maserati',
            'Maxus',
            'Maybach',
            'Mazda',
            'Mazzanti',
            'McLaren',
            'Mercedes-Benz',
            'MG',
            'Mini',
            'Mitsubishi',
            'Mitsuoka',
            'Morgan',
            'Morris',
            'NIO',
            'Nissan',
            'Noble',
            'Opel',
            'Pagani',
            'Perodua',
            'Peugeot',
            'Polestar',
            'Pontiac',
            'Porsche',
            'Proton',
            'Ram',
            'Reliant',
            'Renault',
            'Rimac',
            'Rivian',
            'Rolls-Royce',
            'RUF',
            'Saab',
            'Saleen',
            'Saturn',
            'Scion',
            'SEAT',
            'Senova',
            'SIN Cars',
            'Skoda',
            'Smart',
            'Spyker',
            'SsangYong',
            'Subaru',
            'Suzuki',
            'Tata',
            'Tatra',
            'Tesla',
            'Toyota',
            'Trumpchi',
            'TVR',
            'Vauxhall',
            'VinFast',
            'Volkswagen',
            'Volvo',
            'W Motors',
            'Wiesmann',
            'Zenos',
            'Zenvo',
        ];

        foreach ($brands as $brand) {
            Brand::firstOrCreate(['name' => $brand]);
        }
    }
}